## Introduction

This notebook includes my solutions to introductory SQL exercises. I connected the Northwind_SPP database from SQL Server to Jupyter Notebook so I can run and document all queries here.

You will see the SQL code, results, and short explanations for each exercise.

In [1]:
!pip install pyodbc
!pip install sqlalchemy
!pip install pandas

Requirement already satisfied: pyodbc in c:\users\roger\anaconda3\lib\site-packages (4.0.34)
Requirement already satisfied: sqlalchemy in c:\users\roger\anaconda3\lib\site-packages (2.0.39)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\roger\anaconda3\lib\site-packages (from sqlalchemy) (2.0.1)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\roger\anaconda3\lib\site-packages (from sqlalchemy) (4.7.1)
Requirement already satisfied: pandas in c:\users\roger\anaconda3\lib\site-packages (2.1.4)
Requirement already satisfied: numpy<2,>=1.23.2 in c:\users\roger\anaconda3\lib\site-packages (from pandas) (1.24.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\roger\anaconda3\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\roger\anaconda3\lib\site-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in c:\users\roger\anaconda3\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in c:\users\roger\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [2]:
import pyodbc
import pandas as pd

conn = pyodbc.connect(
    'DRIVER={ODBC Driver 17 for SQL Server};'
    'SERVER=MSI;'
    'DATABASE=Northwind_SPP;'   # The name of the Database
    'Trusted_Connection=yes;'
)

query = "SELECT TOP 5 * FROM Categories"  #Let's run a query to confirm everything is fine.
df = pd.read_sql(query, conn)
df

C:\Users\roger\AppData\Local\Temp\ipykernel_24140\4024251190.py:12: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)

,CategoryID,CategoryName,Description
0,1,Beverages,"Soft drinks, coffees, teas, beers, and ales"
1,2,Condiments,"Sweet and savory sauces, relishes, spreads, an..."
2,3,Confections,"Desserts, candies, and sweet breads"
3,4,Dairy Products,Cheeses
4,5,Grains/Cereals,"Breads, crackers, pasta, and cereal"


<div style="background-color:#e8f4fd; border-left:5px solid #0071bc; padding:10px;">
    <b>Explanation:</b>  Now, We use <b> SQLAlchemy </b> together with <b> pandas </b>to query our SQL Server database directly from Jupyter. This allows us to run SQL queries, load the results into DataFrames, and continue the analysis in Python without switching tools.
</div>

In [3]:
from sqlalchemy import create_engine
import pandas as pd

# Creating engine with SQLAlchemy
engine = create_engine(
    "mssql+pyodbc://@MSI/Northwind_SPP?driver=ODBC+Driver+17+for+SQL+Server&trusted_connection=yes"
)

# Query
query = "SELECT TOP 5 * FROM Categories"

df = pd.read_sql(query, engine)

df

,CategoryID,CategoryName,Description
0,1,Beverages,"Soft drinks, coffees, teas, beers, and ales"
1,2,Condiments,"Sweet and savory sauces, relishes, spreads, an..."
2,3,Confections,"Desserts, candies, and sweet breads"
3,4,Dairy Products,Cheeses
4,5,Grains/Cereals,"Breads, crackers, pasta, and cereal"

Great! Now we are ready to start solving our exercises.

***
### 1) Which shipper do we have?

<div style="background-color:#f5f5f5; border-left:5px solid #0071bc; padding:10px;">
<b>Task:</b> We have a table called Shippers. Return all the fields from all the shippers
</div>

In [7]:
query = """
SELECT
    ShipperID, 
    CompanyName,
    Phone
FROM Shippers;
"""
df = pd.read_sql(query, engine)
df

   ShipperID       CompanyName           Phone
0          1    Speedy Express  (503) 555-9831
1          2    United Package  (503) 555-3199
2          3  Federal Shipping  (503) 555-9931



<div style="background-color:#e8f4fd; border-left:5px solid #0071bc; padding:10px;">
<b>Explanation:</b>  The Shippers table has three Shippers Companies, the table above shows the ShipperID, CompanyName and Phone number for each shippers. Also, I could use the <b>" * "</b> in the SELECT Clause to return every columns from Shipper table but <b> is a better practice putting the exactly name of the columns. </b>
</div>

***
### 2) Certain fields from Categories

<div style="background-color:#f5f5f5; border-left:5px solid #0071bc; padding:10px;">
<b>Task:</b> In the Categories table, selecting all the the field. We only want to see two columns, CategoryName and Description.
</div>

In [9]:
query = """
SELECT 
    CategoryName,
    Description
FROM Categories
"""
df = pd.read_sql(query, engine)
df

     CategoryName                                        Description
0       Beverages        Soft drinks, coffees, teas, beers, and ales
1      Condiments  Sweet and savory sauces, relishes, spreads, an...
2     Confections                Desserts, candies, and sweet breads
3  Dairy Products                                            Cheeses
4  Grains/Cereals                Breads, crackers, pasta, and cereal
5    Meat/Poultry                                     Prepared meats
6         Produce                          Dried fruit and bean curd
7         Seafood                                   Seaweed and fish

<div style="background-color:#e8f4fd; border-left:5px solid #0071bc; padding:10px;">
This table presents the different categories and their descriptions used by the company in the market.
</div>

***
### 3) Sales Representatives

<div style="background-color:#f5f5f5; border-left:5px solid #0071bc; padding:10px;">
<b>Task:</b> We'd like to see just the FirstName, LastName, and HireDate of all the employees with the title of Sales Representative.
</div>

In [13]:
query = """
SELECT 
    FirstName, 
    LastName, 
    HireDate
FROM Employees
WHERE Title = 'Sales Representative'  
ORDER BY HireDate ; 
"""
df = pd.read_sql(query, engine)
df

  FirstName   LastName   HireDate
0     Janet  Leverling 2010-04-01
1     Nancy    Davolio 2010-05-01
2  Margaret    Peacock 2011-05-03
3   Michael     Suyama 2011-10-17
4    Robert       King 2012-01-02
5      Anne  Dodsworth 2012-11-15

<div style="background-color:#e8f4fd; border-left:5px solid #0071bc; padding:10px;">
    <b>Explanation:</b> I used 'Sales Representative' in the <b> WHERE </b> clause as a filter. So, I could get any employee with the <b>Sales Representative</b> title in the company. <b>ORDER BY </b> Sorts the results (Ascending order is for default).
</div>

***
### 4) Sales Representatives in the United States

<div style="background-color:#f5f5f5; border-left:5px solid #0071bc; padding:10px;">
<b>Task:</b> Now we'd like to see the same columns as above, but only for those employees that both have the title of Sales Representative, and also are in the United States.
</div>

In [16]:
query = """
SELECT 
    FirstName,
    LastName,
    HireDate
FROM Employees
WHERE Title = 'Sales Representative'
     AND Country = 'USA'
ORDER BY HireDate ;
"""
df = pd.read_sql(query, engine)
df

  FirstName   LastName   HireDate
0     Janet  Leverling 2010-04-01
1     Nancy    Davolio 2010-05-01
2  Margaret    Peacock 2011-05-03

<div style="background-color:#e8f4fd; border-left:5px solid #0071bc; padding:10px;">
<b>Explanation:</b> You can notice that I used the same query as above to solving the exercise, except for the <b> AND </b> that it is a <b> CONDITIONAL </b> function that helps me to add another filter in my query. In this case, It added USA (United States).
</div>

***
### 5) Orders placed by specific EmployeeID

<div style="background-color:#f5f5f5; border-left:5px solid #0071bc; padding:10px;">
<b>Task:</b> Show all the orders placed by a specific employee. The EmployeeID for this Employee (Steven Buchanan) is 5.
</div>

In [85]:
query = """
SELECT 
    OrderID,  
    CAST(OrderDate AS DATE) AS OrderDate
FROM Orders
WHERE EmployeeID = 5
ORDER BY OrderDate ;

"""
df = pd.read_sql(query, engine)
df

    OrderID   OrderDate
0     10248  2014-07-04
1     10254  2014-07-11
2     10269  2014-07-31
3     10297  2014-09-04
4     10320  2014-10-03
5     10333  2014-10-18
6     10358  2014-11-20
7     10359  2014-11-21
8     10372  2014-12-04
9     10378  2014-12-10
10    10397  2014-12-27
11    10463  2015-03-04
12    10474  2015-03-13
13    10477  2015-03-17
14    10529  2015-05-07
15    10549  2015-05-27
16    10569  2015-06-16
17    10575  2015-06-20
18    10607  2015-07-22
19    10648  2015-08-28
20    10649  2015-08-28
21    10650  2015-08-29
22    10654  2015-09-02
23    10675  2015-09-19
24    10711  2015-10-21
25    10714  2015-10-22
26    10721  2015-10-29
27    10730  2015-11-05
28    10761  2015-12-02
29    10812  2016-01-02
30    10823  2016-01-09
31    10841  2016-01-20
32    10851  2016-01-26
33    10866  2016-02-03
34    10869  2016-02-04
35    10870  2016-02-04
36    10872  2016-02-05
37    10874  2016-02-06
38    10899  2016-02-20
39    10922  2016-03-03
40    10954  2016-03-17
41    11043  2016-04-22

<div style="background-color:#e8f4fd; border-left:5px solid #0071bc; padding:10px;">
<b>Explanation:</b> In this exercise, I need to look for all the orders placed by <b>Employee 5 </b>. In order to accomplish this, I filtered the dataset using the condition WHERE EmployeeID = 5 to retrieve only the relevant records. Adittionaly, I have used the CAST function that allows changing the format of my date column in "YYYY MM DD" format.
</div>

***
### 6) Suppliers and ContactTitles

<div style="background-color:#f5f5f5; border-left:5px solid #0071bc; padding:10px;">
<b>Task:</b> In the Suppliers table, show the SupplierID, ContactName, and ContactTitle for those Suppliers whose ContactTitle is not Marketing Manager.
</div>

In [17]:
query = """
SELECT 
    SupplierID,
    ContactName, 
    ContactTitle
FROM Suppliers
WHERE ContactTitle <>'Marketing Manager' 
ORDER BY SupplierID ;
"""  

df = pd.read_sql(query, engine)
df

    SupplierID                 ContactName                  ContactTitle
0            1            Charlotte Cooper            Purchasing Manager
1            2               Shelley Burke           Order Administrator
2            3               Regina Murphy          Sales Representative
3            5  Antonio del Valle Saavedra          Export Administrator
4            6                 Mayumi Ohno      Marketing Representative
5            8                Peter Wilson          Sales Representative
6            9               Lars Peterson                   Sales Agent
7           11               Petra Winkler                 Sales Manager
8           12                 Martin Bein  International Marketing Mgr.
9           13               Sven Petersen   Coordinator Foreign Markets
10          14                  Elio Rossi          Sales Representative
11          16               Cheryl Saylor         Regional Account Rep.
12          17               Michael Björn          Sales Representative
13          18              Guylène Nodier                 Sales Manager
14          19               Robb Merchant       Wholesale Account Agent
15          20                Chandra Leka                         Owner
16          21              Niels Petersen                 Sales Manager
17          22                 Dirk Luchte            Accounting Manager
18          23              Anne Heikkonen               Product Manager
19          24             Wendy Mackenzie          Sales Representative
20          26            Giovanni Giudici           Order Administrator
21          27              Marie Delamare                 Sales Manager
22          28                  Eliane Noz          Sales Representative
23          29              Chantal Goulet            Accounting Manager

<div style="background-color:#e8f4fd; border-left:5px solid #0071bc; padding:10px;">
<b>Explanation:</b> I solved this exercise in a similar way to the previous one, making only slight changes in the WHERE clause.
    One of these changes was adding the <b> <> operator </b>, which means <b>“not equal to.” </b>
    This condition <b>excludes</b> any employee whose title is <b>Marketing Manager.</b> Also, You can use WHERE NOT ContactTitle = 'Marketing Manager' in order to excluse "Marketing Manager rol" from the results.
</div>

***
### 7) Products with "queso" in ProductName

<div style="background-color:#f5f5f5; border-left:5px solid #0071bc; padding:10px;">
<b>Task:</b> In the products table, we'd like to see the ProductID and ProductName for those products where the ProductName includes the string "queso".
</div>

In [28]:
query = """
SELECT 
    ProductID, 
    ProductName
FROM Products
WHERE ProductName LIKE '%queso%'
ORDER BY 1 ;
"""
df= pd.read_sql(query, engine)
df

   ProductID                ProductName
0         11             Queso Cabrales
1         12  Queso Manchego La Pastora

<div style="background-color:#e8f4fd; border-left:5px solid #0071bc; padding:10px;">
    <b>Explanation:</b> Here, I used the condition <b> LIKE '%queso%' </b> to search for any product name that contains the word <b>"queso"</b>. Placing queso between the percentage <b>symbols (%) </b> means that it can appear anywhere within the text — at the beginning, middle, or end of the product description.
</div>

***
### 8) Orders shipping to France or Belgium

<div style="background-color:#f5f5f5; border-left:5px solid #0071bc; padding:10px;">
<b>Task:</b> Looking at the Orders Table, there's field called ShipCountry.Write a query that shows the OrderID, CustomerID, and ShipCountry for the orders where the ShipCountry is either France or Belgium.
</div>

In [29]:
query = """
SELECT
    OrderID, 
    CustomerID,
    ShipCountry
FROM Orders
WHERE ShipCountry in ('France', 'Belgium')
ORDER BY 1 ;
""" # We can use the filter 'or'
df = pd.read_sql (query, engine)
df

    OrderID CustomerID ShipCountry
0     10248      VINET      France
1     10251      VICTE      France
2     10252      SUPRD     Belgium
3     10265      BLONP      France
4     10274      VINET      France
..      ...        ...         ...
91    11035      SUPRD     Belgium
92    11038      SUPRD     Belgium
93    11043      SPECD      France
94    11051      LAMAI      France
95    11076      BONAP      France

[96 rows x 3 columns]

<div style="background-color:#e8f4fd; border-left:5px solid #0071bc; padding:10px;">
    <b>Explanation:</b> Using the <b> IN operator </b> helped me group and filter only the countries I needed for this exercise.
</div>

***
### 9) Orders shipping to any country in Latin America

<div style="background-color:#f5f5f5; border-left:5px solid #0071bc; padding:10px;">
<b>Task:</b> Now, instead of just wanting to return all the orders from France or Belgium, we want to show all the orders from any Latin American country.But we don't have a list of Latin American countries in a table in the Northwind database. So, we're going to just use the list of Latin American countries that happen to be in the Orders table: Brazil, Mexico, Argentina and Venezuela.
</div>

In [30]:
query = """
SELECT 
    OrderID, 
    CustomerID, 
    ShipCountry
FROM Orders
WHERE ShipCountry IN ('Brazil', 'Mexico', 'Argentina', 'Venezuela')
ORDER BY OrderID ;
"""
df = pd.read_sql(query, engine)
df

     OrderID CustomerID ShipCountry
0      10250      HANAR      Brazil
1      10253      HANAR      Brazil
2      10256      WELLI      Brazil
3      10257      HILAA   Venezuela
4      10259      CENTC      Mexico
..       ...        ...         ...
168    11065      LILAS   Venezuela
169    11068      QUEEN      Brazil
170    11069      TORTU      Mexico
171    11071      LILAS   Venezuela
172    11073      PERIC      Mexico

[173 rows x 3 columns]

<div style="background-color:#e8f4fd; border-left:5px solid #0071bc; padding:10px;">
<b>Explanation:</b> Similar to the previous exercise, I used the <b>IN</b> operator again. I also created a bar chart to illustrate the insight more clearly.
</div>

***
### 10) Employees, in order of age

<div style="background-color:#f5f5f5; border-left:5px solid #0071bc; padding:10px;">
<b>Task:</b> For all the employees in the Employees table, show the FirstName, LastName, Title, and BirthDate.Order the results by BirthDate, so we have the oldest employees first.
</div>

In [31]:
query = """
SELECT 
    FirstName, 
    LastName, 
    Title, BirthDate
FROM Employees
ORDER BY BirthDate;
"""

df = pd.read_sql (query, engine)
df

  FirstName   LastName                     Title  BirthDate
0  Margaret    Peacock      Sales Representative 1955-09-19
1     Nancy    Davolio      Sales Representative 1966-12-08
2    Andrew     Fuller     Vice President, Sales 1970-02-19
3    Steven   Buchanan             Sales Manager 1973-03-04
4     Laura   Callahan  Inside Sales Coordinator 1976-01-09
5    Robert       King      Sales Representative 1978-05-29
6   Michael     Suyama      Sales Representative 1981-07-02
7     Janet  Leverling      Sales Representative 1981-08-30
8      Anne  Dodsworth      Sales Representative 1984-01-27

<div style="background-color:#e8f4fd; border-left:5px solid #0071bc; padding:10px;">
<b>Explanation:</b> To solving this exercise you only need to sort by the <b> BirthDate </b> column. It sorts in asceding order by default.
</div>

***
### 11) Employees full name 

<div style="background-color:#f5f5f5; border-left:5px solid #0071bc; padding:10px;">
<b>Task:</b> Show the FirstName and LastName columns from the Employees table, and then create a new column called FullName, Showing FirstName and LastName joined together in one column, with a space in-between.
</div>

In [32]:
query = """
SELECT 
    FirstName,
    LastName,
    CONCAT (FirstName, ' ', LastName) as FullName
FROM Employees
ORDER BY FullName;
"""
df = pd.read_sql(query, engine)
df

  FirstName   LastName          FullName
0    Andrew     Fuller     Andrew Fuller
1      Anne  Dodsworth    Anne Dodsworth
2     Janet  Leverling   Janet Leverling
3     Laura   Callahan    Laura Callahan
4  Margaret    Peacock  Margaret Peacock
5   Michael     Suyama    Michael Suyama
6     Nancy    Davolio     Nancy Davolio
7    Robert       King       Robert King
8    Steven   Buchanan   Steven Buchanan

<div style="background-color:#e8f4fd; border-left:5px solid #0071bc; padding:10px;">
    <b>Explanation:</b> the function <b> CONCAT </b> helps me to mix the columns <b> FirstName </b> and <b> LastName </b>. To create a space between the firstname and lastname I used " ". 
</div>

***
### 12) OrderDetails amount per line item

<div style="background-color:#f5f5f5; border-left:5px solid #0071bc; padding:10px;">
<b>Task:</b> In the OrderDetails table, we have the fields UnitPrice and Quantity. Creat a new field, TotalPrice, that multiplies these two together. We'll ignore the Discount field for now. In addition, show the OrderID, ProductID, UnitPrice, and Quantity. Order by OrderID and ProductID.
</div>

In [33]:
query = """
SELECT 
    OrderID, 
    ProductID, 
    UnitPrice, 
    Quantity,
    (UnitPrice * Quantity) as TotalPrice
FROM OrderDetails
ORDER BY OrderID, ProductID ;
"""
df = pd.read_sql(query, engine)
df

      OrderID  ProductID  UnitPrice  Quantity  TotalPrice
0       10248         11      14.00        12       168.0
1       10248         42       9.80        10        98.0
2       10248         72      34.80         5       174.0
3       10249         14      18.60         9       167.4
4       10249         51      42.40        40      1696.0
...       ...        ...        ...       ...         ...
2150    11077         64      33.25         2        66.5
2151    11077         66      17.00         1        17.0
2152    11077         73      15.00         2        30.0
2153    11077         75       7.75         4        31.0
2154    11077         77      13.00         2        26.0

[2155 rows x 5 columns]

<div style="background-color:#e8f4fd; border-left:5px solid #0071bc; padding:10px;">
<b>Explanation:</b> To solve this exercise I needed to multiple UnitPrice by Quantity. I named the columns with the results as TotalPrice with the function <b> AS</b>.
</div>

***
### 13. How many customers?

<div style="background-color:#f5f5f5; border-left:5px solid #0071bc; padding:10px;">
<b>Task:</b> How many customers do we have in the Customers table? Show one value only, and don't rely on getting the record count at the end of a resultset
</div>

In [34]:
query = """
SELECT 
    COUNT(DISTINCT(CustomerID)) AS TotalCustomers
FROM Customers ;
"""
df = pd.read_sql(query, engine)
df

   TotalCustomers
0              91

<div style="background-color:#e8f4fd; border-left:5px solid #0071bc; padding:10px;">
    <b>Explanation:</b> I used the Aggregation function <b> COUNT </b> to count the number of customer the company has. Finally, I used function <b> DISTINCT </b> to avoid duplicates.
</div>

***
### 14) When was the first order?

<div style="background-color:#f5f5f5; border-left:5px solid #0071bc; padding:10px;">
<b>Task:</b> Show the date of the first order ever made in the Orders table.
</div>

In [35]:
query = """
SELECT
    MIN (OrderDate) AS FirstOrder
FROM Orders
"""
df = pd.read_sql(query, engine)
df

           FirstOrder
0 2014-07-04 08:00:00

<div style="background-color:#e8f4fd; border-left:5px solid #0071bc; padding:10px;">
    <b>Explanation:</b> The <b> MIN  </b> helps to look for the oldest date.
</div>

***
### 15) Countries where there are customers

<div style="background-color:#f5f5f5; border-left:5px solid #0071bc; padding:10px;">
<b>Task:</b> Show a list of countries where Northwind company has customers.
</div>

In [36]:
query = """
SELECT 
    Country
From Customers
WHERE Country IS NOT NULL
GROUP BY Country
ORDER BY Country ;
"""
df = pd.read_sql(query, engine)
df

        Country
0     Argentina
1       Austria
2       Belgium
3        Brazil
4        Canada
5       Denmark
6       Finland
7        France
8       Germany
9       Ireland
10        Italy
11       Mexico
12       Norway
13       Poland
14     Portugal
15        Spain
16       Sweden
17  Switzerland
18           UK
19          USA
20    Venezuela

<div style="background-color:#e8f4fd; border-left:5px solid #0071bc; padding:10px;">
<b>Explanation:</b> In this excersices, I used the IS NOT NULL condition in the WHERE clause to avoid Null values in my results.
</div>

***
### 16) Contact titles for customers

<div style="background-color:#f5f5f5; border-left:5px solid #0071bc; padding:10px;">
<b>Task:</b> Show a list of all the different values in the Customers table for ContactTitles. Also include a count for each ContactTile. 
</div>

In [37]:
query = """
SELECT 
    ContactTitle,
    COUNT(*) AS TotalContactTitle
FROM Customers
GROUP BY ContactTitle
ORDER BY TotalContactTitle DESC ;
"""
df = pd.read_sql(query, engine)
df

                      ContactTitle  TotalContactTitle
0                            Owner                 17
1             Sales Representative                 17
2                Marketing Manager                 12
3                    Sales Manager                 11
4               Accounting Manager                 10
5                  Sales Associate                  7
6              Marketing Assistant                  6
7                      Sales Agent                  5
8            Assistant Sales Agent                  2
9              Order Administrator                  2
10  Assistant Sales Representative                  1
11       Owner/Marketing Assistant                  1

<div style="background-color:#e8f4fd; border-left:5px solid #0071bc; padding:10px;">
<b>Explanation:</b> Here, I counted the numbers the titles per each group. I needed to use the Aggregation function COUNT to count every title and Grouping By ContactTitle, I was counting every title per each group.
</div>

***
### 17) Products with associated supplier names

<div style="background-color:#f5f5f5; border-left:5px solid #0071bc; padding:10px;">
<b>Task:</b> We'd like to show, for each product, the associated Supplier. Show the ProductID, ProductName, and the Company Name of the Supplier. Sort the result by ProductID.
</div>

In [38]:
query = """
SELECT 
    p.ProductID, p.ProductName,
    s.CompanyName
FROM Products AS p

JOIN Suppliers AS s
ON p.SupplierID = s.SupplierID

ORDER BY ProductID ;

"""

df = pd.read_sql(query, engine)
df

,ProductID,ProductName,CompanyName
0,1,Chai,Exotic Liquids
1,2,Chang,Exotic Liquids
2,3,Aniseed Syrup,Exotic Liquids
3,4,Chef Anton's Cajun Seasoning,New Orleans Cajun Delights
4,5,Chef Anton's Gumbo Mix,New Orleans Cajun Delights
...,...,...,...
72,73,Röd Kaviar,Svensk Sjöföda AB
73,74,Longlife Tofu,Tokyo Traders
74,75,Rhönbräu Klosterbier,Plutzer Lebensmittelgroßmärkte AG
75,76,Lakkalikööri,Karkki Oy
76,77,Original Frankfurter grüne Soße,Plutzer Lebensmittelgroßmärkte AG

<div style="background-color:#e8f4fd; border-left:5px solid #0071bc; padding:10px;">
<b>Explanation:</b> I joined two table using the function JOIN and the primary key for both table, SupplierID. This allows me to take the columns I needed and connect them in one query.
</div>

***
### 18) Orders and the Shipper that was used

<div style="background-color:#f5f5f5; border-left:5px solid #0071bc; padding:10px;">
<b>Task:</b> We'd like to show a list of the Orders that were made, including the Shipper that was used. Show the OrderID,OrderDate (date only), and CompanyName of the Shipper, and sort by OrderID.

In order to not show all the orders (there's more than 800), show only those rows with an OrderID of less than 10270.
</div>

In [39]:
query = """
SELECT 
    o.OrderID, CAST(o.OrderDate AS DATE) AS OrderDate, 
    s.CompanyName AS Shipper
FROM Orders AS o

JOIN Shippers AS s
ON o.ShipVia = s.ShipperID

WHERE o.OrderID < 10270
ORDER BY 1 ;
"""
df = pd.read_sql(query, engine)
df

    OrderID   OrderDate           Shipper
0     10248  2014-07-04  Federal Shipping
1     10249  2014-07-05    Speedy Express
2     10250  2014-07-08    United Package
3     10251  2014-07-08    Speedy Express
4     10252  2014-07-09    United Package
5     10253  2014-07-10    United Package
6     10254  2014-07-11    United Package
7     10255  2014-07-12  Federal Shipping
8     10256  2014-07-15    United Package
9     10257  2014-07-16  Federal Shipping
10    10258  2014-07-17    Speedy Express
11    10259  2014-07-18  Federal Shipping
12    10260  2014-07-19    Speedy Express
13    10261  2014-07-19    United Package
14    10262  2014-07-22  Federal Shipping
15    10263  2014-07-23  Federal Shipping
16    10264  2014-07-24  Federal Shipping
17    10265  2014-07-25    Speedy Express
18    10266  2014-07-26  Federal Shipping
19    10267  2014-07-29    Speedy Express
20    10268  2014-07-30  Federal Shipping
21    10269  2014-07-31    Speedy Express


<div style="background-color:#e8f4fd; border-left:5px solid #0071bc; padding:10px;">
<b>Explanation:</b> This exercise is similiar to the above. Although, I used the function CAST to remove the timestamp of my OrderDate column. In addition, I want to highligt a tricky situacion in the primary key. The primary key has different name in the both table. Shipvia for Orders table and ShipperID for Shippers table.
</div>

***
# Intermediate Problems

***
### 20) Categories, and the total products in each category

<div style="background-color:#f5f5f5; border-left:5px solid #0071bc; padding:10px;">
<b>Task:</b> For this problem, we'd like to see the total number of products in each category. Sort the results by the total number of products, in descending order.
</div>

In [44]:
query = """
SELECT 
    c.CategoryName,
    COUNT(*) AS TotalProducts 
FROM Products AS p

JOIN Categories AS c 
ON p.CategoryID = c.CategoryID 

GROUP BY c.CategoryName
ORDER BY TotalProducts DESC; --Sorting by TotalProducts in descending order.
"""
df = pd.read_sql(query, engine)
df

     CategoryName  TotalProducts
0     Confections             13
1       Beverages             12
2      Condiments             12
3         Seafood             12
4  Dairy Products             10
5  Grains/Cereals              7
6    Meat/Poultry              6
7         Produce              5

<div style="background-color:#e8f4fd; border-left:5px solid #0071bc; padding:10px;">
<b>Explanation:</b> First,Aggregation function to count products per each category. Second, I labeled the Products table as p and I labeled the Categories table as c. Then, I'm joining the tables creating a relationship using CategoryID. Finally,sorting by TotalProducts in descending order.
</div>

***
### 21) Total customers per country/city

<div style="background-color:#f5f5f5; border-left:5px solid #0071bc; padding:10px;">
<b>Task:</b> In the Customers table, show the total number of customers per Country and City.
</div>

In [41]:
query = """
SELECT 
    Country, 
    City,
    COUNT(*) AS TotalCustomers
FROM Customers
GROUP BY Country, City
ORDER BY TotalCustomers DESC
"""
df = pd.read_sql(query, engine)
df

        Country            City  TotalCustomers
0            UK          London               6
1        Mexico     México D.F.               5
2        Brazil       Sao Paulo               4
3        Brazil  Rio de Janeiro               3
4         Spain          Madrid               3
..          ...             ...             ...
64  Switzerland            Bern               1
65          USA           Boise               1
66       Sweden          Bräcke               1
67      Germany     Brandenburg               1
68      Belgium       Bruxelles               1

[69 rows x 3 columns]

<div style="background-color:#e8f4fd; border-left:5px solid #0071bc; padding:10px;">
<b>Explanation:</b> I counted every customer per Country and City and I grouped by Country and City.
</div>

***
### 22) Products that need reordering

<div style="background-color:#f5f5f5; border-left:5px solid #0071bc; padding:10px;">
<b>Task:</b> What products do we have in our inventory that should be reordered? For now, just use the fields UnitsInStock and ReorderLevel, where UnitsInStock is less than or equal to the ReorderLevel, Ignore the fields UnitsOnOrder and Discontinued. Sort the resullts by ProductID.
</div>

In [40]:
query = """
SELECT 
    ProductID, 
    ProductName, 
    UnitsInStock, 
    ReorderLevel
FROM Products
WHERE UnitsInStock <= ReorderLevel
ORDER BY ProductID ;
"""
df = pd.read_sql(query, engine)
df

    ProductID                ProductName  UnitsInStock  ReorderLevel
0           2                      Chang            17            25
1           3              Aniseed Syrup            13            25
2           5     Chef Anton's Gumbo Mix             0             0
3          11             Queso Cabrales            22            30
4          17               Alice Mutton             0             0
5          21        Sir Rodney's Scones             3             5
6          29    Thüringer Rostbratwurst             0             0
7          30      Nord-Ost Matjeshering            10            15
8          31          Gorgonzola Telino             0            20
9          32         Mascarpone Fabioli             9            25
10         37                 Gravad lax            11            25
11         43                Ipoh Coffee            17            25
12         45                Rogede sild             5            15
13         48                  Chocolade            15            25
14         49                   Maxilaku            10            15
15         53              Perth Pasties             0             0
16         56     Gnocchi di nonna Alice            21            30
17         64  Wimmers gute Semmelknödel            22            30
18         66  Louisiana Hot Spiced Okra             4            20
19         68        Scottish Longbreads             6            15
20         70              Outback Lager            15            30
21         74              Longlife Tofu             4             5

<div style="background-color:#e8f4fd; border-left:5px solid #0071bc; padding:10px;">
<b>Explanation:</b> In this exercise, I used the CONDITION <= to when UnitsInStock is less than or equal to the ReorderLevel.
</div>

***
### 23) Products that need reordering, continued

<div style="background-color:#f5f5f5; border-left:5px solid #0071bc; padding:10px;">
<b>Task:</b> Now we need to incorporate these fields -UnitsInStock, UnitsOnOrder, ReorderLevel, Discontinued - into our calculation. We'll define "products that need reordering" with the following:
1) UnitsInStock plus UnitsOnOrder are less than or equal to ReorderLevel.
2) The Discontinued flag is false (0).
</div>

In [166]:
query = """
SELECT 
    ProductID, 
    UnitsInStock, 
    UnitsOnOrder, 
    ReorderLevel,
    Discontinued
FROM Products
WHERE UnitsInStock + UnitsOnOrder <= ReorderLevel
    AND Discontinued = 0
ORDER BY 1 ;
"""
df = pd.read_sql(query, engine)
df

   ProductID  UnitsInStock  UnitsOnOrder  ReorderLevel  Discontinued
0         30            10             0            15         False
1         70            15            10            30         False

<div style="background-color:#e8f4fd; border-left:5px solid #0071bc; padding:10px;">
<b>Explanation:</b> Similar to the exercise above. I am just using two CONDITION in the where clause and connecting them with the connector AND. 
</div>

***
### 24) Customer list by Region

<div style="background-color:#f5f5f5; border-left:5px solid #0071bc; padding:10px;">
<b>Task:</b> A salesperson for Northwind is going on a business trip to visit customers, and would like to see a list of all customers, sorted by region alphabetically. However, he wants the customers with no region (null in the Region field) to be at the end, instead of at the top, where you'd normally find the null values. Within the same region, companies should be sorte by CustomerID.
</div>

In [45]:
query= """
SELECT 
    CustomerID,
    CompanyName, 
    Region
FROM Customers
ORDER BY CASE 
    WHEN Region IS NULL THEN 1 ELSE 0 END,
    Region;
"""
df = pd.read_sql(query,engine)
df

   CustomerID                    CompanyName    Region
0       OLDWO         Old World Delicatessen        AK
1       LAUGB  Laughing Bacchus Wine Cellars        BC
2       BOTTM          Bottom-Dollar Markets        BC
3       LETSS              Let's Stop N Shop        CA
4       HUNGO   Hungry Owl All-Night Grocers  Co. Cork
..        ...                            ...       ...
86      WARTH                 Wartian Herkku      None
87      WILMK                    Wilman Kala      None
88      WOLZA                 Wolski  Zajazd      None
89      TOMSP             Toms Spezialitäten      None
90      TORTU            Tortuga Restaurante      None

[91 rows x 3 columns]

<div style="background-color:#e8f4fd; border-left:5px solid #0071bc; padding:10px;">
<b>Explanation:</b> Here, I needed to sort every none vaule at the end. This has been solved using a WHEN CASE scenario where every Nulls value is equal 1, every else equal to zero. So, when I sort per Region in ascending order the Nulls value would be at the end of the table.
</div>

***
### 25) High freight charges

<div style="background-color:#f5f5f5; border-left:5px solid #0071bc; padding:10px;">
<b>Task:</b> Some of the countries we ship to have very high freight charges. We'd like to investigate some more shipping options of our customers, to be able to offer them lower freight chargers. Return the three ship countries with the highest average freight overrall, in descending order by average freight.
</div>

In [46]:
query= """
SELECT TOP 3 
    ShipCountry, ROUND(AVG(Freight),2) AS avg_freight
FROM Orders
GROUP BY ShipCountry
ORDER BY avg_freight DESC;
"""
df = pd.read_sql(query,engine)
df

  ShipCountry  avg_freight
0     Austria       184.79
1     Ireland       145.01
2         USA       112.88

In [47]:
query= """
SELECT  
    ShipCountry,
    ROUND(AVG(Freight),2) AS avg_freight
FROM Orders
GROUP BY ShipCountry
ORDER BY avg_freight DESC;
"""
df = pd.read_sql(query,engine)
df

    ShipCountry  avg_freight
0       Austria       184.79
1       Ireland       145.01
2           USA       112.88
3       Germany        92.49
4        Sweden        87.50
5        France        80.72
6       Denmark        77.57
7   Switzerland        76.03
8        Canada        73.27
9       Belgium        67.38
10    Venezuela        59.46
11       Brazil        58.80
12           UK        52.75
13     Portugal        49.50
14       Norway        45.92
15      Finland        41.40
16       Mexico        40.10
17        Spain        37.47
18    Argentina        37.41
19        Italy        30.87
20       Poland        25.11

<div style="background-color:#e8f4fd; border-left:5px solid #0071bc; padding:10px;">
<b>Explanation:</b> I am using an aggregation function AVG and the function ROUND(...,2) to only get two decimals.
</div>

***
### 26) High freight charges - 2015

<div style="background-color:#f5f5f5; border-left:5px solid #0071bc; padding:10px;">
<b>Task:</b> We're continuing on the question above on high freight charges. Now, instead of using all the orders we have, we only want to see orders from the year 2015
</div>

In [48]:
query= """
SELECT  
    ShipCountry, 
    ROUND(AVG(Freight),2) AS avg_freight
FROM Orders
WHERE Year(OrderDate) = 2015
GROUP BY ShipCountry
ORDER BY avg_freight DESC;
"""
df = pd.read_sql(query,engine)
df

    ShipCountry  avg_freight
0       Austria       178.36
1   Switzerland       117.18
2        France       113.99
3        Sweden       105.16
4        Canada        99.28
5       Ireland        98.08
6       Germany        97.38
7           USA        96.99
8       Denmark        94.62
9     Venezuela        71.04
10      Belgium        65.78
11       Brazil        53.00
12       Mexico        52.96
13       Poland        52.22
14      Finland        48.93
15        Spain        42.42
16           UK        39.62
17     Portugal        39.21
18        Italy        29.38
19       Norway        26.01
20    Argentina        19.61

<div style="background-color:#e8f4fd; border-left:5px solid #0071bc; padding:10px;">
<b>Explanation:</b> Similar to above, I only had to filter  Year(OrderDate) = 2015, for only get the result from 2015. Notice that I used the function YEAR before (OrderDate), that because I was extracting only the year from the OrderDate column.
</div>

***
### 27) High freight charges with between

<div style="background-color:#f5f5f5; border-left:5px solid #0071bc; padding:10px;">
<b>Task:</b> Another(incorrect) answer to the problem above is this: Notice when you run this, it shows Sweden as the ShipCountry with the third highest freight charges. However, this is wrong it should be France. What is the OrderID of the order that the (incorrect) answer above is missing?
</div>

In [49]:
query= """
SELECT  
    ShipCountry, 
    ROUND(AVG(Freight),2) AS avg_freight
FROM Orders
WHERE OrderDate BETWEEN '20150101' AND '20160101' 
GROUP BY ShipCountry
ORDER BY avg_freight DESC;
"""
df = pd.read_sql(query,engine)
df

    ShipCountry  avg_freight
0       Austria       178.36
1   Switzerland       117.18
2        France       113.99
3        Sweden       105.16
4        Canada        99.28
5       Ireland        98.08
6       Germany        97.38
7           USA        96.99
8       Denmark        94.62
9     Venezuela        71.04
10      Belgium        65.78
11       Brazil        53.00
12       Mexico        52.96
13       Poland        52.22
14      Finland        48.93
15        Spain        42.42
16           UK        39.62
17     Portugal        39.21
18        Italy        29.38
19       Norway        26.01
20    Argentina        19.61

***
### 28) High freight charges - last year

<div style="background-color:#f5f5f5; border-left:5px solid #0071bc; padding:10px;">
<b>Task:</b> We're continuing to work on high freight charges. We now want to get the three ship countries with the highest average freight charges. But instead of filtering for a particular year, we want to use the last 12 months or order data, using as the end date the last OrderDate in Orders.
</div>

In [50]:
query= """
SELECT 
    TOP 3 
    ShipCountry,
    ROUND(AVG(Freight),2) AS avg_freight
FROM Orders
WHERE OrderDate >= DATEADD(MONTH, -12, (SELECT MAX(OrderDate) FROM Orders))
GROUP BY ShipCountry
ORDER BY avg_freight DESC;
"""
df = pd.read_sql(query,engine)
df

  ShipCountry  avg_freight
0     Ireland       200.21
1     Austria       186.46
2         USA       119.30

<div style="background-color:#e8f4fd; border-left:5px solid #0071bc; padding:10px;">
<b>Explanation:</b> This query identifies the top three countries with the highest average freight cost over the last 12 months. It filters recent orders based on the most current order date, calculates the average freight per country, rounds the result to two decimals, and sorts them in descending order to highlight the top performers.
</div>

***
### 29) Employee/Order Detail report

<div style="background-color:#f5f5f5; border-left:5px solid #0071bc; padding:10px;">
<b>Task:</b>We're doing inventory, and need to show Employee and Order Detail information like the below, for all orders. Sort by OrderID and Product.
</div>

In [51]:
query= """
SELECT 
    e.EmployeeID, e.LastName, 
    o.OrderID, 
    p.ProductName, 
    od.Quantity
FROM Employees AS e

JOIN Orders AS o
ON e.EmployeeID = o.EmployeeID

JOIN OrderDetails AS od
ON o.OrderID = od.OrderID

JOIN Products AS p
ON p.ProductID = od.ProductID

ORDER BY o.OrderID, od.Quantity DESC 
"""
df = pd.read_sql(query,engine)
df

      EmployeeID  LastName  OrderID                      ProductName  Quantity
0              5  Buchanan    10248                   Queso Cabrales        12
1              5  Buchanan    10248    Singaporean Hokkien Fried Mee        10
2              5  Buchanan    10248           Mozzarella di Giovanni         5
3              6    Suyama    10249            Manjimup Dried Apples        40
4              6    Suyama    10249                             Tofu         9
...          ...       ...      ...                              ...       ...
2150           1   Davolio    11077     Grandma's Boysenberry Spread         1
2151           1   Davolio    11077  Uncle Bob's Organic Dried Pears         1
2152           1   Davolio    11077               Mascarpone Fabioli         1
2153           1   Davolio    11077           Sir Rodney's Marmalade         1
2154           1   Davolio    11077        Louisiana Hot Spiced Okra         1

[2155 rows x 5 columns]

<div style="background-color:#e8f4fd; border-left:5px solid #0071bc; padding:10px;">
<b>Explanation:</b> This query connects multiple tables to display which employees handled each order and the products included in those orders. It joins the Employees, Orders, OrderDetails, and Products tables to show details such as employee name, order ID, product name, and quantity. Finally, the results are sorted by order ID and then by quantity in descending order to highlight the largest items per order.
</div>

***
### 30) Customers with no orders

<div style="background-color:#f5f5f5; border-left:5px solid #0071bc; padding:10px;">
<b>Task:</b> There are some customers who have never actually placed an order. Show these customers.
</div>

In [24]:
query= """
SELECT 
    c.CustomerID,
    o.OrderID
FROM Customers AS c

LEFT OUTER JOIN Orders AS o
ON c.CustomerID = o.CustomerID

WHERE o.CustomerID IS NULL
"""
df= pd.read_sql(query,engine)
df

  CustomerID OrderID
0      PARIS    None
1      FISSA    None

<div style="background-color:#e8f4fd; border-left:5px solid #0071bc; padding:10px;">
<b>Explanation:</b> This query identifies customers who have never placed an order. It uses a LEFT JOIN between the Customers and Orders tables and filters the results where no matching order exists (o.CustomerID IS NULL). This helps highlight inactive or new customers who haven’t made a purchase yet.
</div>

***
### 31) Customers with no orders for EmployeeID

<div style="background-color:#f5f5f5; border-left:5px solid #0071bc; padding:10px;">
<b>Task:</b> One employee(Margatet Peacock, EmployeeID 4) has placed the most orders. However, there are some customers who've never placed an order with her. Show only those customers who have never placed an order with her.
</div>

In [25]:
query= """
SELECT 
    o.CustomerID, 
    c.CustomerID
FROM Orders AS o

LEFT JOIN Customers as c
ON o.CustomerID = c.CustomerID AND o.EmployeeID = 4

WHERE c.CustomerID IS NULL
ORDER BY o.CustomerID;
"""
df= pd.read_sql(query,engine)
df

    CustomerID CustomerID
0        ALFKI       None
1        ALFKI       None
2        ALFKI       None
3        ALFKI       None
4        ANATR       None
..         ...        ...
669      WOLZA       None
670      WOLZA       None
671      WOLZA       None
672      WOLZA       None
673      WOLZA       None

[674 rows x 2 columns]

<div style="background-color:#e8f4fd; border-left:5px solid #0071bc; padding:10px;">
<b>Explanation:</b> This query finds customers who have placed orders, but none of those orders were handled by Employee 4. It performs a LEFT JOIN between Orders and Customers based on the customer ID, while specifically matching only orders managed by Employee 4. The condition c.CustomerID IS NULL filters out customers served by that employee, leaving only those who weren’t. The results are then ordered by customer ID for clarity.
</div>

***
## Advanced Problems

***
### 31. High-value customers

<div style="background-color:#f5f5f5; border-left:5px solid #0071bc; padding:10px;">
<b>Task:</b> We want to send all of our high-value customers a special VIP gift. We're defining high-vale customers as those who've made at least 1 order with a total value (not including the discount) equal to $10,000 or more. We only want to consider orders made in the year 2016.
</div>

In [26]:
query= """
SELECT 
    o.OrderID, c.CompanyName, 
    SUM(od.UnitPrice * od.Quantity) AS TotalOrderAmount
FROM Orders AS o

JOIN Customers AS c
ON o.CustomerID = c.CustomerID

JOIN OrderDetails AS od
ON o.OrderID = od.OrderID

WHERE o.OrderDate >= '20160101' AND OrderDate < '20170101' 
GROUP BY o.OrderID, c.CompanyName
HAVING SUM(od.UnitPrice * od.Quantity) >= 10000 AND COUNT(o.OrderID) >= 1
ORDER BY TotalOrderAmount DESC ;

"""
df = pd.read_sql(query,engine)
df

   OrderID                   CompanyName  TotalOrderAmount
0    10865                    QUICK-Stop          17250.00
1    11030            Save-a-lot Markets          16321.90
2    10981                 Hanari Carnes          15810.00
3    10817               Königlich Essen          11490.70
4    10889    Rattlesnake Canyon Grocery          11380.00
5    10897  Hungry Owl All-Night Grocers          10835.24

#### Another solution using CTE

In [27]:
query= """
WITH Total AS (
SELECT o.OrderID, c.CompanyName, SUM(od.UnitPrice * od.Quantity) AS TotalOrderAmount
FROM Orders AS o
JOIN Customers AS c
ON o.CustomerID = c.CustomerID
JOIN OrderDetails AS od
ON o.OrderID = od.OrderID
WHERE o.OrderDate >= '20160101' AND o.OrderDate < '20170101' 
GROUP BY o.OrderID, c.CompanyName )

SELECT *
FROM Total
WHERE TotalOrderAmount >= 10000
ORDER BY TotalOrderAmount DESC;
"""
df = pd.read_sql(query,engine)
df

   OrderID                   CompanyName  TotalOrderAmount
0    10865                    QUICK-Stop          17250.00
1    11030            Save-a-lot Markets          16321.90
2    10981                 Hanari Carnes          15810.00
3    10817               Königlich Essen          11490.70
4    10889    Rattlesnake Canyon Grocery          11380.00
5    10897  Hungry Owl All-Night Grocers          10835.24

<div style="background-color:#e8f4fd; border-left:5px solid #0071bc; padding:10px;">
<b>Explanation:</b> This query highlights high-value orders from the year 2016. It joins the Orders, Customers, and OrderDetails tables to calculate the total amount per order by multiplying unit price and quantity. The results are grouped by order and company, and only orders worth $10,000 or more are included using the HAVING clause. Finally, the query sorts the data in descending order to showcase the largest orders first. <b> Remember that you need to add CustomerID </b>
</div>

***
### 32) High-value customers-Total Orders

<div style="background-color:#f5f5f5; border-left:5px solid #0071bc; padding:10px;">
<b>Task:</b> The manager has changed his mind. Instead of requiring that customers have at least one individual order totaling 10,000 or more, he wants to define high-value customers differently. Now, high value customers are customers who have orders totaling 15,000 or more in 2016. How would you the answer to the problem above? 
</div>

In [346]:
query= """
SELECT c.CustomerID, c.CompanyName, SUM(od.UnitPrice * od.Quantity) AS TotalOrderAmount
FROM Orders AS o
JOIN Customers AS c
ON o.CustomerID = c.CustomerID
JOIN OrderDetails AS od
ON o.OrderID = od.OrderID
WHERE o.OrderDate >= '20160101' AND OrderDate < '20170101' 
GROUP BY c.CustomerID, c.CompanyName
HAVING SUM(od.UnitPrice * od.Quantity) >= 15000 AND COUNT(od.OrderID) >= 2
ORDER BY TotalOrderAmount DESC ;

"""

df = pd.read_sql(query,engine)
df

  CustomerID                   CompanyName  TotalOrderAmount
0      SAVEA            Save-a-lot Markets          42806.25
1      ERNSH                  Ernst Handel          42598.90
2      QUICK                    QUICK-Stop          40526.99
3      HANAR                 Hanari Carnes          24238.05
4      HUNGO  Hungry Owl All-Night Grocers          22796.34
5      RATTC    Rattlesnake Canyon Grocery          21725.60
6      KOENE               Königlich Essen          20204.95
7      FOLKO                Folk och fä HB          15973.85
8      WHITC          White Clover Markets          15278.90

<div style="background-color:#e8f4fd; border-left:5px solid #0071bc; padding:10px;">
<b>Explanation:</b> This query identifies customers who generated at least $15,000 in total sales and made two or more orders during 2016. It joins the Orders, Customers, and OrderDetails tables, calculates each customer’s total order value, and groups the results by customer ID and company name. Using the HAVING clause, it filters only those who meet both conditions, then sorts them in descending order of total sales to highlight the most valuable customers of the year.
</div>

***
### 33. High-Value customers -with discount 

<div style="background-color:#f5f5f5; border-left:5px solid #0071bc; padding:10px;">
<b>Task:</b> Change the answer from the previous problem to use the discount when calculating high-value customers. Order by the total amount, taking into consideration the discount. 
</div>

In [363]:
query = """
SELECT 
    c.CustomerID,
    c.CompanyName,
    SUM(od.UnitPrice * od.Quantity) AS Totals_Without_Discount,
    ROUND(SUM(od.UnitPrice * od.Quantity *(1 - od.Discount)),2) AS Totals_With_Discount #Discount is applied as a percentage.
FROM Customers AS c
JOIN Orders AS o
    ON c.CustomerID = o.CustomerID
JOIN OrderDetails AS od
    ON o.OrderID = od.OrderID
WHERE o.OrderDate >= '20160101' AND o.OrderDate < '20170101' 
GROUP BY c.CustomerID, c.CompanyName
HAVING  SUM(od.UnitPrice * od.Quantity) >= 15000
    AND COUNT(o.OrderID) >= 2
ORDER BY Totals_With_Discount DESC;
"""
df = pd.read_sql(query,engine)
df

,CustomerID,CompanyName,Totals_Without_Discount,Totals_With_Discount
0,ERNSH,Ernst Handel,42598.90,41210.65
1,QUICK,QUICK-Stop,40526.99,37217.32
2,SAVEA,Save-a-lot Markets,42806.25,36310.11
3,HANAR,Hanari Carnes,24238.05,23821.20
4,RATTC,Rattlesnake Canyon Grocery,21725.60,21238.27
5,HUNGO,Hungry Owl All-Night Grocers,22796.34,20402.12
6,KOENE,Königlich Essen,20204.95,19582.77
7,WHITC,White Clover Markets,15278.90,15278.90
8,FOLKO,Folk och fä HB,15973.85,13644.07

<div style="background-color:#e8f4fd; border-left:5px solid #0071bc; padding:10px;">
<b>Explanation:</b> This query compares total customer sales with and without discounts for the year 2016. It joins the Customers, Orders, and OrderDetails tables to calculate two metrics: total sales before discounts and total sales after applying the discount percentage. Only customers with at least $15,000 in total sales and two or more orders are included, using the HAVING clause. Finally, results are sorted by total sales with discount in descending order to highlight the top revenue-generating customers after discounts.
</div>

***
### 34.Month-end orders

<div style="background-color:#f5f5f5; border-left:5px solid #0071bc; padding:10px;">
<b>Task:</b> At the end of the month, salespeople are likely to try much harder to get orders, to meet their month-end quotas. Show all orders made on the last day of the month. Order by EmployeeID and OrderID.
</div>

In [368]:
query = """
SELECT 
    EmployeeID,
    OrderID,
    OrderDate
FROM Orders
WHERE OrderDate = EOMONTH(OrderDate)
Order By EmployeeID, OrderID ;
"""
df= pd.read_sql(query, engine)
df

    EmployeeID  OrderID  OrderDate
0            1    10461 2015-02-28
1            1    10616 2015-07-31
2            2    10583 2015-06-30
3            2    10686 2015-09-30
4            2    10989 2016-03-31
5            2    11060 2016-04-30
6            3    10432 2015-01-31
7            3    10988 2016-03-31
8            3    11063 2016-04-30
9            4    10343 2014-10-31
10           4    10522 2015-04-30
11           4    10584 2015-06-30
12           4    10617 2015-07-31
13           4    10725 2015-10-31
14           4    11061 2016-04-30
15           4    11062 2016-04-30
16           5    10269 2014-07-31
17           6    10317 2014-09-30
18           7    10490 2015-03-31
19           8    10399 2014-12-31
20           8    10460 2015-02-28
21           8    10491 2015-03-31
22           8    10987 2016-03-31
23           9    10687 2015-09-30

<div style="background-color:#e8f4fd; border-left:5px solid #0071bc; padding:10px;">
<b>Explanation:</b> This query retrieves all orders that were placed on the last day of each month. It selects the EmployeeID, OrderID, and OrderDate from the Orders table, using the EOMONTH function to filter only month-end orders. The results are ordered by employee and order ID to make it easy to track which employees handled month-end transactions.
</div>

***
### 35. Orders with many line items

<div style="background-color:#f5f5f5; border-left:5px solid #0071bc; padding:10px;">
<b>Task:</b> The Northwind mobile app developers are testing an app that customer will use to show orders. In order to make sure that even the largest orders will show up correctly on the app, they'd like some samples of orders that have lost of individual line items. Show the 10 orders with the most line items, in order of total line items.
</div>

In [372]:
query = """
SELECT 
    TOP 10
    OrderID,
    COUNT(OrderID) AS TotalOrders
FROM OrderDetails
GROUP BY OrderID
ORDER BY TotalOrders DESC;
"""
df = pd.read_sql(query,engine)
df

   OrderID  TotalOrders
0    11077           25
1    10657            6
2    10847            6
3    10979            6
4    10273            5
5    10294            5
6    10309            5
7    10324            5
8    10325            5
9    10337            5

<div style="background-color:#e8f4fd; border-left:5px solid #0071bc; padding:10px;">
<b>Explanation:</b> This query identifies the top 10 orders with the highest number of items. It counts the number of entries per OrderID in the OrderDetails table, groups the results by order, and sorts them in descending order to highlight the orders containing the most products.
</div>

***
### 36. Orders - random assortment

<div style="background-color:#f5f5f5; border-left:5px solid #0071bc; padding:10px;">
<b>Task:</b> The Northwind mobile app developers would now like to just get a random assortment of orders for beta testing on their app. Show a random set of 2% of all orders.
</div>

In [185]:
query = """
SELECT 
    TOP 2 PERCENT
    OrderID
FROM Orders
ORDER BY NEWID()
"""
df = pd.read_sql(query, engine)
df

    OrderID
0     10747
1     11013
2     10915
3     10258
4     10384
5     10706
6     11077
7     10958
8     10535
9     10862
10    10948
11    10473
12    10460
13    11022
14    10260
15    10626
16    10939

<div style="background-color:#e8f4fd; border-left:5px solid #0071bc; padding:10px;">
<b>Explanation:</b> This query selects a random sample of the top 2% of orders from the Orders table. The NEWID() function generates a unique identifier for each row, which is used to randomly shuffle the orders before selecting the top 2%. This technique is useful for sampling data without bias.
</div>

***
### 37.Orders - accidental double - entry

<div style="background-color:#f5f5f5; border-left:5px solid #0071bc; padding:10px;">
<b>Task:</b> One of the salespeople has come to you with a request. She thinks that she accidentally entered a line item twice on an order, each time with a different ProductID, but the exact same quatity. She remembers that the quantity was 60 or more. Show all the OrderIDs with line items that match this, in order of OrderID.
</div>

In [410]:
query = """
SELECT 
    OrderID,
    Quantity,
    COUNT(OrderID) AS Total_Order_IDs
FROM OrderDetails
WHERE Quantity >= 60
GROUP BY OrderID, Quantity
HAVING COUNT(OrderID) > 1
ORDER BY OrderID;
"""
df = pd.read_sql (query, engine)
df

   OrderID  Quantity  Total_Order_IDs
0    10263        60                2
1    10263        65                2
2    10658        70                2
3    10990        65                2
4    11030       100                2

<div style="background-color:#e8f4fd; border-left:5px solid #0071bc; padding:10px;">
<b>Explanation:</b> This query identifies orders that include large quantities of the same product. It filters OrderDetails for rows where Quantity is 60 or more, groups the data by OrderID and Quantity, and counts how many times each order ID appears. Only orders where the same quantity appears more than once are included, and the results are sorted by OrderID for clarity.
</div>

***
### 39. Orders - accidental double-entry details

<div style="background-color:#f5f5f5; border-left:5px solid #0071bc; padding:10px;">
<b>Task:</b> Based on the previous question, we now want to show details of the order, for orders that match the above criteria.
</div>

In [186]:

query = """
WITH Orders_Duplicated
AS 
(
    SELECT
        OrderID,
        Quantity,
        COUNT(OrderID) AS Total_Order_IDs
    FROM OrderDetails
    WHERE Quantity >= 60
    GROUP BY OrderID, Quantity
    HAVING COUNT(OrderID) > 1
)

SELECT
    od.OrderID,
    od.ProductID,
    od.UnitPrice,
    od.Quantity,
    od.Discount
FROM Orders_Duplicated AS o
    JOIN OrderDetails AS od
    ON o.OrderID = od.OrderID
    AND o.Quantity = od.Quantity
ORDER BY od.OrderID;
"""
df = pd.read_sql (query, engine)
df

   OrderID  ProductID  UnitPrice  Quantity  Discount
0    10263         16       13.9        60      0.25
1    10263         30       20.7        60      0.25
2    10263         24        3.6        65      0.00
3    10263         74        8.0        65      0.25
4    10658         40       18.4        70      0.05
5    10658         77       13.0        70      0.05
6    10990         21       10.0        65      0.00
7    10990         55       24.0        65      0.15
8    11030          2       19.0       100      0.25
9    11030         59       55.0       100      0.25

<div style="background-color:#e8f4fd; border-left:5px solid #0071bc; padding:10px;">
<b>Explanation:</b> This query builds on identifying orders with duplicate large quantities. First, a CTE (Orders_Duplicated) filters OrderDetails for orders where the same Quantity appears more than once and is at least 60 units. Then, it joins back to OrderDetails to retrieve full details of these orders, including ProductID, UnitPrice, Quantity, and Discount. The results are ordered by OrderID, providing a detailed view of high-quantity duplicate orders.
</div>

***
### 40. Late Orders

<div style="background-color:#f5f5f5; border-left:5px solid #0071bc; padding:10px;">
<b>Task:</b> Some customer are complaining about their orders arriving late. Wich orders are late. Sort the results by OrderID.
</div>

In [414]:
query = """
SELECT
    OrderID,
    CustomerID,
    OrderDate,
    RequiredDate, 
    ShippedDate
FROM Orders
WHERE RequiredDate <= ShippedDate
ORDER BY OrderID;   
"""
df = pd.read_sql(query,engine)
df

    OrderID CustomerID           OrderDate RequiredDate ShippedDate
0     10264      FOLKO 2014-07-24 22:00:00   2014-08-21  2014-08-23
1     10271      SPLIR 2014-08-01 05:00:00   2014-08-29  2014-08-30
2     10280      BERGS 2014-08-14 10:00:00   2014-09-11  2014-09-12
3     10302      SUPRD 2014-09-10 17:00:00   2014-10-08  2014-10-09
4     10309      HUNGO 2014-09-19 14:00:00   2014-10-17  2014-10-23
5     10380      HUNGO 2014-12-12 19:00:00   2015-01-09  2015-01-16
6     10423      GOURL 2015-01-23 01:00:00   2015-02-06  2015-02-24
7     10427      PICCO 2015-01-27 06:00:00   2015-02-24  2015-03-03
8     10433      PRINI 2015-02-03 09:00:00   2015-03-03  2015-03-04
9     10451      QUICK 2015-02-19 08:00:00   2015-03-05  2015-03-12
10    10483      WHITC 2015-03-24 07:00:00   2015-04-21  2015-04-25
11    10515      QUICK 2015-04-23 17:00:00   2015-05-07  2015-05-23
12    10523      SEVES 2015-05-01 13:00:00   2015-05-29  2015-05-30
13    10545      LAZYK 2015-05-22 14:00:00   2015-06-19  2015-06-26
14    10578      BSBEV 2015-06-24 15:00:00   2015-07-22  2015-07-25
15    10593      LEHMS 2015-07-09 10:00:00   2015-08-06  2015-08-13
16    10596      WHITC 2015-07-11 06:00:00   2015-08-08  2015-08-12
17    10660      HUNGC 2015-09-08 03:00:00   2015-10-06  2015-10-15
18    10663      BONAP 2015-09-10 12:00:00   2015-09-24  2015-10-03
19    10687      HUNGO 2015-09-30 00:00:00   2015-10-28  2015-10-30
20    10705      HILAA 2015-10-15 19:00:00   2015-11-12  2015-11-18
21    10709      GOURL 2015-10-17 13:00:00   2015-11-14  2015-11-20
22    10726      EASTC 2015-11-03 05:00:00   2015-11-17  2015-12-05
23    10727      REGGC 2015-11-03 20:00:00   2015-12-01  2015-12-05
24    10749      ISLAT 2015-11-20 00:00:00   2015-12-18  2015-12-19
25    10777      GOURL 2015-12-15 08:00:00   2015-12-29  2016-01-21
26    10779      MORGK 2015-12-16 04:00:00   2016-01-13  2016-01-14
27    10788      QUICK 2015-12-22 01:00:00   2016-01-19  2016-01-19
28    10807      FRANS 2015-12-31 11:00:00   2016-01-28  2016-01-30
29    10816      GREAL 2016-01-06 22:00:00   2016-02-03  2016-02-04
30    10827      BONAP 2016-01-12 19:00:00   2016-01-26  2016-02-06
31    10828      RANCH 2016-01-13 04:00:00   2016-01-27  2016-02-04
32    10847      SAVEA 2016-01-22 08:00:00   2016-02-05  2016-02-10
33    10924      BERGS 2016-03-04 20:00:00   2016-04-01  2016-04-08
34    10927      LACOR 2016-03-05 08:00:00   2016-04-02  2016-04-08
35    10960      HILAA 2016-03-19 15:00:00   2016-04-02  2016-04-08
36    10970      BOLID 2016-03-24 09:00:00   2016-04-07  2016-04-24
37    10978      MAISD 2016-03-26 10:00:00   2016-04-23  2016-04-23
38    10998      WOLZA 2016-04-03 00:00:00   2016-04-17  2016-04-17

<div style="background-color:#e8f4fd; border-left:5px solid #0071bc; padding:10px;">
<b>Explanation:</b> This query identifies orders that were shipped after or on their required date. It selects key order details—OrderID, CustomerID, OrderDate, RequiredDate, and ShippedDate—from the Orders table and filters for cases where the ShippedDate is later than or equal to the RequiredDate. The results are ordered by OrderID to easily track shipments that met or exceeded their required timelines.
</div>

***
### 41. Late Orders - which employees? 

<div style="background-color:#f5f5f5; border-left:5px solid #0071bc; padding:10px;">
<b>Task:</b> Some salespeople have more orders arriving late than others. Maybe they're not following up on the order process, and need more training. Which salespeople have the most orders arriving late?
</div>

In [427]:
query = """
SELECT 
    e.EmployeeID, e.LastName,
    COUNT(o.OrderID) AS Total_late_orders
FROM Employees AS e
JOIN Orders AS o
ON e.EmployeeID = o.EmployeeID
WHERE o.RequiredDate <= o.ShippedDate 
GROUP BY e.EmployeeID, e.LastName
ORDER BY Total_late_orders DESC ;
"""
df = pd.read_sql(query,engine)
df

   EmployeeID   LastName  Total_late_orders
0           4    Peacock                 10
1           3  Leverling                  5
2           8   Callahan                  5
3           9  Dodsworth                  5
4           7       King                  4
5           2     Fuller                  4
6           1    Davolio                  3
7           6     Suyama                  3

The chart here

<div style="background-color:#e8f4fd; border-left:5px solid #0071bc; padding:10px;">
<b>Explanation:</b> This query shows which employees had the most late shipments. It joins Employees and Orders, counts orders where the ShippedDate is later than or equal to the RequiredDate, and groups the results by employee ID and last name. The results are sorted in descending order to highlight employees responsible for the highest number of late orders.
</div>

***
### 42. Late orders vs. total orders

<div style="background-color:#f5f5f5; border-left:5px solid #0071bc; padding:10px;">
<b>Task:</b> Andrew, the VP of sales, has been doing some more thinking about the problem of late orders. He realizes that just looking at the number of orders arriving late for each salesperson isn't a good idea. It needs to be compared to the total number of orders per salesperson.
</div>

In [462]:
query = """
SELECT
    e.EmployeeID,
    e.LastName,
    COUNT(DISTINCT o.OrderID) AS Total_Orders,
    SUM(CASE WHEN o.ShippedDate IS NOT NULL AND o.ShippedDate > o.RequiredDate THEN 1 ELSE 0 END) AS Late_Orders
FROM Orders AS o
JOIN Employees AS e
    ON o.EmployeeID = e.EmployeeID
GROUP BY e.EmployeeID, e.LastName
ORDER BY e.EmployeeID;

"""

df = pd.read_sql(query, engine)
df

   EmployeeID   LastName  Total_Orders  Late_Orders
0           1    Davolio           123            2
1           2     Fuller            96            4
2           3  Leverling           127            5
3           4    Peacock           156           10
4           5   Buchanan            42            0
5           6     Suyama            67            3
6           7       King            72            4
7           8   Callahan           104            4
8           9  Dodsworth            43            4

<div style="background-color:#e8f4fd; border-left:5px solid #0071bc; padding:10px;">
<b>Explanation:</b> This query summarizes each employee’s order performance, counting total distinct orders and late shipments using a CASE WHEN statement. Results are grouped by employee and ordered by EmployeeID, providing a clear overview of workload and timeliness.
</div>

***
### 43. Late orders vs. total orders - percentage

<div style="background-color:#f5f5f5; border-left:5px solid #0071bc; padding:10px;">
<b>Task:</b> Now, we want to get the percetange of late orders over total orders.
</div>

In [464]:
query = """
WITH Orders_Status AS
(
    SELECT 
        e.EmployeeID, e.LastName,
        COUNT(DISTINCT o.OrderID) AS Total_Orders,
        SUM(CASE WHEN o.ShippedDate IS NOT NULL AND o.ShippedDate > RequiredDate THEN 1 ELSE 0 END) AS Late_Orders,
        SUM(CASE WHEN o.ShippedDate IS NOT NULL AND o.ShippedDate <= RequiredDate THEN 1 ELSE 0 END) AS On_Time_Orders
    FROM Orders AS o
    JOIN Employees AS e ON o.EmployeeID = e.EmployeeID
    GROUP BY e.EmployeeID, e.LastName
)

SELECT EmployeeID, LastName, Total_Orders, Late_Orders, On_Time_Orders,
    ROUND(CAST(COALESCE(Late_Orders,0) AS FLOAT)/NULLIF(Total_Orders,0),2) AS Late_Ratio,
    ROUND(CAST(COALESCE(On_Time_Orders,0) AS FLOAT)/NULLIF(Total_Orders,0),2) AS On_Time_Ratio
FROM Orders_Status
ORDER BY EmployeeID;
"""
df = pd.read_sql(query,engine)
df

,EmployeeID,LastName,Total_Orders,Late_Orders,On_Time_Orders,Late_Ratio,On_Time_Ratio
0,1,Davolio,123,2,118,0.02,0.96
1,2,Fuller,96,4,89,0.04,0.93
2,3,Leverling,127,5,122,0.04,0.96
3,4,Peacock,156,10,141,0.06,0.90
4,5,Buchanan,42,0,42,0.00,1.00
5,6,Suyama,67,3,62,0.04,0.93
6,7,King,72,4,65,0.06,0.90
7,8,Callahan,104,4,96,0.04,0.92
8,9,Dodsworth,43,4,38,0.09,0.88

<div style="background-color:#e8f4fd; border-left:5px solid #0071bc; padding:10px;">
<b>Explanation:</b> This query provides a detailed performance summary for each employee. Using a CTE (Orders_Status), it calculates the total number of orders, late orders, and on-time orders per employee. The final query then computes the late and on-time ratios by dividing the respective counts by total orders, rounding to two decimals. Results are ordered by EmployeeID, giving a clear view of each employee’s timeliness and overall performance.
</div>

***

### 44. Customer grouping

<div style="background-color:#f5f5f5; border-left:5px solid #0071bc; padding:10px;">
<b>Task:</b> Andrew Fuller, the VIP of sales at Northwind, would like to do a sales campaign for existing customers. He'd like to categorize customers into groups, based on how much they ordered in 2016. Then, depending on which group the customer is in, he will target the customer with different sales materials.

The customer grouping categories are 0 to 1,000; 1,000 to 5,000; 5,000 to 10,000; and Over 10,000. So, if the total dollar amount of the customer's purchases in that year were between 0 to 1,000, they would be in the "Low" group. A customer with purchase from 1,000 to 5,000 would be in the "Medium" group, and so on. Also, we only want to show customers who have ordered in 2016.
</div>

In [14]:
query= """
SELECT 
    c.CustomerID, c.CompanyName,
    COALESCE(SUM(od.UnitPrice * od.Quantity),0) AS Total_Orders,
    CASE 
        WHEN COALESCE(SUM(od.UnitPrice * od.Quantity),0) BETWEEN 0 AND 999 THEN 'Low' 
        WHEN COALESCE(SUM(od.UnitPrice * od.Quantity),0) BETWEEN 1000 AND 4999 THEN 'Medium'
        WHEN COALESCE(SUM(od.UnitPrice * od.Quantity),0) BETWEEN 5000 AND 9999 THEN 'High'
        ELSE 'Very High' 
    END AS Customer_Group
FROM Customers AS c
JOIN Orders AS o 
    ON c.CustomerID = o.CustomerID
JOIN OrderDetails AS od
    ON od.OrderID = o.OrderID
WHERE o.OrderDate >= '2016-01-01'  AND o.OrderDate < '2017-01-01'
GROUP BY c.CustomerID, c.CompanyName
ORDER BY c.CustomerID ;
"""
df = pd.read_sql(query,engine)
df

   CustomerID                         CompanyName  Total_Orders Customer_Group
0       ALFKI                 Alfreds Futterkiste       2302.20         Medium
1       ANATR  Ana Trujillo Emparedados y helados        514.40            Low
2       ANTON             Antonio Moreno Taquería        660.00            Low
3       AROUT                     Around the Horn       5838.50           High
4       BERGS                  Berglunds snabbköp       8110.55           High
..        ...                                 ...           ...            ...
76      WARTH                      Wartian Herkku        300.00            Low
77      WELLI              Wellington Importadora       1245.00         Medium
78      WHITC                White Clover Markets      15278.90      Very High
79      WILMK                         Wilman Kala       1987.00         Medium
80      WOLZA                      Wolski  Zajazd       1865.10         Medium

[81 rows x 4 columns]

Chart here.

<div style="background-color:#e8f4fd; border-left:5px solid #0071bc; padding:10px;">
<b>Explanation:</b> This query classifies customers based on their total order value for the year 2016. It joins Customers, Orders, and OrderDetails to calculate total sales per customer, using COALESCE to handle customers with no orders. A CASE statement categorizes customers into Low, Medium, High, or Very High groups based on their total purchase amount. The results are grouped by customer and ordered by CustomerID, providing a clear view of customer value segments.
</div>

***
### 45. Customer grouping with percentage

<div style="background-color:#f5f5f5; border-left:5px solid #0071bc; padding:10px;">
<b>Task:</b> Based on the above query, show all the defined CustomerGroups, and the percentage in each. Sort by the total in each group, in descending order.
</div>

In [28]:
query= """
WITH Group_Summary AS
(
    SELECT 
        c.CustomerID, c.CompanyName,
        COALESCE(SUM(od.UnitPrice * od.Quantity),0) AS Total_Orders,
        CASE 
            WHEN COALESCE(SUM(od.UnitPrice * od.Quantity),0) BETWEEN 0 AND 999 THEN 'Low' 
            WHEN COALESCE(SUM(od.UnitPrice * od.Quantity),0) BETWEEN 1000 AND 4999 THEN 'Medium'
            WHEN COALESCE(SUM(od.UnitPrice * od.Quantity),0) BETWEEN 5000 AND 9999 THEN 'High'
        ELSE 'Very High' 
    END AS Customer_Group
    FROM Customers AS c
    JOIN Orders AS o 
    ON c.CustomerID = o.CustomerID
    JOIN OrderDetails AS od
    ON od.OrderID = o.OrderID
    WHERE o.OrderDate >= '2016-01-01'  AND o.OrderDate < '2017-01-01'
    GROUP BY c.CustomerID, c.CompanyName
)

SELECT 
    Customer_Group,
    COUNT(CustomerID) AS Number_Of_Customers,
    ROUND(CAST(COUNT(CustomerID) AS FLOAT) / SUM(COUNT(CustomerID)) OVER(),2) AS Percentage
FROM Group_Summary
GROUP BY Customer_Group
ORDER BY Number_Of_Customers DESC;
"""
df = pd.read_sql(query,engine)
df

  Customer_Group  Number_Of_Customers  Percentage
0         Medium                   35        0.43
1            Low                   20        0.25
2           High                   13        0.16
3      Very High                   13        0.16

Chart here

<div style="background-color:#e8f4fd; border-left:5px solid #0071bc; padding:10px;">
<b>Explanation:</b> This query provides an overview of customer distribution by total order value for 2016. First, a CTE (Group_Summary) calculates total orders per customer and assigns each to a customer group (Low, Medium, High, Very High). The final query then counts the number of customers in each group and calculates their percentage of the total customer base, allowing for a clear view of how customers are distributed across value segments.
</div>

***
### 46. Countries with suppliers or customers

<div style="background-color:#f5f5f5; border-left:5px solid #0071bc; padding:10px;">
<b>Task:</b> Some Northwind employees are planning a business trip, and would like to visit as many suppliers and customers as possible. For their planning, they'd like to see a list of all countries where suppliers and/or customers are based.
</div>

In [36]:
query= """
SELECT Country
FROM Customers
UNION 
SELECT Country
From Suppliers 
"""
df = pd.read_sql(query,engine)
df

        Country
0     Argentina
1     Australia
2       Austria
3       Belgium
4        Brazil
5        Canada
6       Denmark
7       Finland
8        France
9       Germany
10      Ireland
11        Italy
12        Japan
13       Mexico
14  Netherlands
15       Norway
16       Poland
17     Portugal
18    Singapore
19        Spain
20       Sweden
21  Switzerland
22           UK
23          USA
24    Venezuela

<div style="background-color:#e8f4fd; border-left:5px solid #0071bc; padding:10px;">
<b>Explanation:</b> This query generates a list of all unique countries represented in the Customers and Suppliers tables. Using UNION, it combines the two datasets and automatically removes duplicates, giving a clear view of all countries involved with the business.
</div>

***
### 47. Countries with suppliers or customers, version 2

<div style="background-color:#f5f5f5; border-left:5px solid #0071bc; padding:10px;">
<b>Task:</b> The employees going on the business trip don't want just a raw list of countries, they want more details. We'd like to see output like the below, in the Expected Results.
</div>

In [38]:
query= """
WITH Suppliers_Country AS
(
    SELECT DISTINCT Country AS Supplier_Country
    FROM Suppliers
),

    Customers_Country AS
(
    SELECT DISTINCT Country  AS Customer_Country
    FROM Customers
)

SELECT s.Supplier_Country, c.Customer_Country
FROM Suppliers_Country AS s
FULL OUTER JOIN Customers_Country AS c
    ON s.Supplier_Country = c.Customer_Country
"""
df = pd.read_sql(query,engine)
df

   Supplier_Country Customer_Country
0              None        Argentina
1         Australia             None
2              None          Austria
3              None          Belgium
4            Brazil           Brazil
5            Canada           Canada
6           Denmark          Denmark
7           Finland          Finland
8            France           France
9           Germany          Germany
10             None          Ireland
11            Italy            Italy
12            Japan             None
13             None           Mexico
14      Netherlands             None
15           Norway           Norway
16             None           Poland
17             None         Portugal
18        Singapore             None
19            Spain            Spain
20           Sweden           Sweden
21             None      Switzerland
22               UK               UK
23              USA              USA
24             None        Venezuela

<div style="background-color:#e8f4fd; border-left:5px solid #0071bc; padding:10px;">
<b>Explanation:</b> This query compares the countries of suppliers and customers. It first creates two CTEs with distinct countries from the Suppliers and Customers tables. Then, a FULL OUTER JOIN combines them to show all countries from both tables, including those that exist only in one of the two datasets. This provides a comprehensive view of geographical overlap and differences between suppliers and customers.
</div>

***
### 48. Countries with suppliers or customers, version 3

<div style="background-color:#f5f5f5; border-left:5px solid #0071bc; padding:10px;">
<b>Task:</b> The output in the above practice problem is improved, but it's still not ideal. What we'd really like to see is the country name, the total suppliers, and the total customers.
</div>

In [47]:
query= """
WITH Suppliers_Data AS
(
    SELECT Country AS Supplier_Country,
        COUNT(*) AS Total_Suppliers
    FROM Suppliers
        GROUP BY Country
 ),

Customers_Data AS
(
        SELECT Country  AS Customer_Country,
        COUNT(*) AS Total_Customers
        FROM Customers
        GROUP BY Country
)

    SELECT 
        COALESCE(s.Supplier_Country,c.Customer_Country) AS Country,
        COALESCE(s.Total_Suppliers, 0) AS Suppliers,
        COALESCE(c.Total_Customers,0) AS Customers
    FROM Suppliers_Data AS s
    FULL OUTER JOIN Customers_Data AS c
        ON s.Supplier_Country = c.Customer_Country
    ORDER BY Country;
    """
    df = pd.read_sql(query,engine)
    df

        Country  Suppliers  Customers
0     Argentina          0          3
1     Australia          2          0
2       Austria          0          2
3       Belgium          0          2
4        Brazil          1          9
5        Canada          2          3
6       Denmark          1          2
7       Finland          1          2
8        France          3         11
9       Germany          3         11
10      Ireland          0          1
11        Italy          2          3
12        Japan          2          0
13       Mexico          0          5
14  Netherlands          1          0
15       Norway          1          1
16       Poland          0          1
17     Portugal          0          2
18    Singapore          1          0
19        Spain          1          5
20       Sweden          2          2
21  Switzerland          0          2
22           UK          2          7
23          USA          4         13
24    Venezuela          0          4

<div style="background-color:#e8f4fd; border-left:5px solid #0071bc; padding:10px;">
<b>Explanation:</b> This query provides a country-level summary of suppliers and customers. Two CTEs calculate the total number of suppliers and customers per country. A FULL OUTER JOIN then combines the data, using COALESCE to handle countries that appear in only one table. The final result shows each country along with the number of suppliers and customers, giving a clear overview of business presence by geography. 
</div>

***
### 49. First order in each country

<div style="background-color:#f5f5f5; border-left:5px solid #0071bc; padding:10px;">
<b>Task:</b> Looking at the Orders table. We'd like to show details for each order that was the first in that particular country, ordered by OrderID.So, for each country, we want one row. That row should contain the earlist order for that country, with the associated ShipCountry, CustomerID, OrderID, and OrderDate.
</div>

In [51]:
query= """
WITH First_Orders AS
(
    SELECT 
        ShipCountry, CustomerID, OrderID, CAST(OrderDate AS DATE) AS OrderDate,
        ROW_NUMBER() OVER(PARTITION BY ShipCountry ORDER BY OrderDate ASC) AS rn
FROM Orders
)

SELECT ShipCountry, CustomerID, OrderID, OrderDate
FROM First_Orders
WHERE rn = 1 ;
"""
df = pd.read_sql(query,engine)
df

    ShipCountry CustomerID  OrderID   OrderDate
0     Argentina      OCEAN    10409  2015-01-09
1       Austria      ERNSH    10258  2014-07-17
2       Belgium      SUPRD    10252  2014-07-09
3        Brazil      HANAR    10250  2014-07-08
4        Canada      MEREP    10332  2014-10-17
5       Denmark      SIMOB    10341  2014-10-29
6       Finland      WARTH    10266  2014-07-26
7        France      VINET    10248  2014-07-04
8       Germany      TOMSP    10249  2014-07-05
9       Ireland      HUNGO    10298  2014-09-05
10        Italy      MAGAA    10275  2014-08-07
11       Mexico      CENTC    10259  2014-07-18
12       Norway      SANTG    10387  2014-12-18
13       Poland      WOLZA    10374  2014-12-05
14     Portugal      FURIB    10328  2014-10-14
15        Spain      ROMEY    10281  2014-08-14
16       Sweden      FOLKO    10264  2014-07-24
17  Switzerland      CHOPS    10254  2014-07-11
18           UK      BSBEV    10289  2014-08-26
19          USA      RATTC    10262  2014-07-22
20    Venezuela      HILAA    10257  2014-07-16

<div style="background-color:#e8f4fd; border-left:5px solid #0071bc; padding:10px;">
<b>Explanation:</b> This query identifies the first order placed in each country. Using a CTE (First_Orders), it assigns a row number to each order per ShipCountry based on the earliest OrderDate. The final query filters for rn = 1 to return only the earliest order per country, providing insight into each country’s initial engagement with the business.
</div>

***
### 50. Customers with multiple orders in 5 day period.

<div style="background-color:#f5f5f5; border-left:5px solid #0071bc; padding:10px;">
<b>Task:</b> There are some customers for whom freight is a major expense when ordering from Northwind.However, by batching up their orders, and making one larger order instead of multiple smaller orders in a short period of time, they could reduce their freight costs significantly. Show those customers who have made more than 1 order in a 5 day period. The salespeople will use this to help customers reduce their freight costs.
</div>

In [66]:
query= """
WITH NextOrders AS
(
    SELECT 
        CustomerID, CAST(OrderDate AS DATE) AS OrderDate,
        CAST(LEAD(OrderDate) OVER (PARTITION BY CustomerID ORDER BY CAST(OrderDate AS DATE) ASC) AS DATE) AS Next_Order_Date
    FROM Orders
)

SELECT
    CustomerID, OrderDate, Next_Order_Date,
     DATEDIFF(day, OrderDate, Next_Order_Date) AS Days_Between_Orders
FROM NextOrders
WHERE DATEDIFF(day, OrderDate, Next_Order_Date) <= 5
ORDER BY OrderDate, CustomerID, Days_Between_Orders;
"""
df = pd.read_sql(query,engine)
df

   CustomerID   OrderDate Next_Order_Date  Days_Between_Orders
0       HANAR  2014-07-08      2014-07-10                    2
1       BERGS  2014-08-12      2014-08-14                    2
2       ROMEY  2014-08-14      2014-08-15                    1
3       QUICK  2014-08-20      2014-08-21                    1
4       RATTC  2014-09-25      2014-09-27                    2
..        ...         ...             ...                  ...
64      SAVEA  2016-04-17      2016-04-17                    0
65      SUPRD  2016-04-20      2016-04-21                    1
66      BOTTM  2016-04-23      2016-04-24                    1
67      EASTC  2016-04-24      2016-04-28                    4
68      LILAS  2016-05-01      2016-05-05                    4

[69 rows x 4 columns]

<div style="background-color:#e8f4fd; border-left:5px solid #0071bc; padding:10px;">
<b>Explanation:</b> This query finds customers who placed another order within 5 days of a previous one. It uses a CTE with the LEAD() function to get each customer's next order date, then calculates the days between orders. Only pairs with 5 or fewer days apart are shown.

</div>